options:
  docker: true

pipelines:
  branches:
    mybranch:
      - step:
          script: # Modify the commands below to build your repository.
            # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
            - export IMAGE_NAME=curranabell/reaction-nmp:latest

            # build the Docker image (this will use the Dockerfile in the root of the repo)
            - docker build -t reaction-nmp .
            # authenticate with the Docker Hub registry
            - docker login --username curranabell --password drz400sm
            # push the new Docker image to the Docker registry
            - docker push reaction-nmp
